<?php
// Set page title.
$pageTitle = 'Social Statistics';
$this->headTitle($this->translate($pageTitle)." - ".$this->translate('VuFind Administration'));

// Set up breadcrumbs:
$breadcrumbs = array();
$breadcrumbs[0]["href"] = $this->url('admin');
$breadcrumbs[0]["text"] = 'VuFind Administration';
$breadcrumbs[1]["text"] = $pageTitle;
$this->layout()->breadcrumbs = $breadcrumbs;

// echo $this->render("Helpers/debug.phtml", ['a' => $this->data]);

?>
<div class="<?=$this->layoutClass('mainbody')?>">

<h1><?=$this->transEsc($pageTitle)?></h1>

<?php foreach ($this->data as $key => $val): ?>
<h2 id="a-socialstats-<?=$key?>"><?=$this->transEsc($val["heading"])?></h2>
<table class="table table-striped" aria-describedby="a-socialstats-<?=$key?>">
  <thead>
    <tr>
    <?php foreach ($val["headers"] as $k => $v): ?>
    <th scope="col" class="text-right"><?=$this->transEsc($v["text"])?></th>
    <?php endforeach; ?>
    </tr>
  </thead>
  <tbody>
    <tr>
    <?php foreach ($val["values"] as $k => $v): ?>
    <td class="text-right"><?=$v["value"]?></td>
    <?php endforeach; ?>
    </tr>
  </tbody>
</table><br/>
<?php endforeach; ?>

</div>

<?=$this->render("admin/sidebar.phtml", ['active' => 'admin-social'])?>