<?php
$i = 0;
$items = array();

$i = 1 + $i;
$items[$i]["text"] = "Deminifier";
$items[$i]["title"] = "Examine minified search data copied from the search database table";
$items[$i]["url"] = $this->url("devtools-deminify");
$items[$i]["active"] = "";

$i = 1 + $i;
$items[$i]["text"] = "Comparing Languages Against English";
$items[$i]["title"] = "Summarize status of translations in language files";
$items[$i]["url"] = $this->url("devtools-language");
$items[$i]["active"] = "";

?>
<?=$this->render("layout/aside-items.phtml", ["items" => $items])?>
