<?php
$pageTitle = 'OAI Server';
$this->headTitle($this->translate($pageTitle));
$this->layout()->breadcrumbs = $this->transEsc($pageTitle);
$baseUrl = $this->url('oai-server');
$this->headScript()->appendFile("lib/toc.js");
$css = 'fieldset{float:none;width:auto;}legend{border:0;margin-bottom:0;}';
$this->headstyle()->appendStyle($css);
?>

<a class="search-filter-toggle visible-xs" href="#aside" data-toggle="offcanvas" title="Expand Sidebar"><?=$this->transEsc('Available Functionality') ?></a>
<div class="<?=$this->layoutClass('mainbody')?>">

<h1><?=$this->transEsc($pageTitle)?></h1>

<p>This OAI server is OAI 2.0 compliant.</p>
<p>The OAI Server URL is: <code><?=$this->serverUrl($baseUrl)?></code></p>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>Identify</legend>
<input type="hidden" name="verb" value="Identify"/>
<p class="help-block">Returns the Identification information of this OAI Server.</p>
<p class="help-block">Accepts no additional parameters.</p>

<button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>ListIdentifiers</legend>

  <input type="hidden" name="verb" value="ListIdentifiers"/>
  <p class="help-block">Returns a listing of available identifiers</p>

  <div class="form-group">
  <label for="ListIdentifier_from" class="control-label"><?=$this->transEsc('From')?>:</label>
  <input id="ListIdentifier_from" type="text" name="from" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListIdentifier_until" class="control-label"><?=$this->transEsc('Until')?>:</label>
  <input id="ListIdentifier_until" type="text" name="until" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListIdentifier_set" class="control-label"><?=$this->transEsc('Set')?>:</label>
  <input id="ListIdentifier_set" type="text" name="set" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListIdentifier_metadataPrefix" class="control-label"><?=$this->transEsc('Metadata Prefix')?>:</label>
  <input id="ListIdentifier_metadataPrefix" type="text" name="metadataPrefix" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListIdentifier_resumptionToken" class="control-label"><?=$this->transEsc('Resumption Token')?>:</label>
  <input id="ListIdentifier_resumptionToken" type="text" name="resumptionToken" class="form-control"/>
  </div>

  <button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>ListMetadataFormats</legend>
  <input type="hidden" name="verb" value="ListMetadataFormats"/>
  <p class="help-block">Returns a listing of available metadata formats.</p>

  <div class="form-group">
  <label for="ListMetadataFormats_identifier" class="control-label"><?=$this->transEsc('Identifier')?>:</label>
  <input id="ListMetadataFormats_identifier" type="text" name="identifier" class="form-control"/>
  </div>

  <button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>ListSets</legend>
  <input type="hidden" name="verb" value="ListSets"/>
  <p class="help-block">Returns a listing of available sets.</p>

  <div class="form-group">
  <label for="ListSets_metadataPrefix" class="control-label"><?=$this->transEsc('Metadata Prefix')?>:</label>
  <input id="ListSets_metadataPrefix" type="text" name="metadataPrefix" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListSets_resumptionToken" class="control-label"><?=$this->transEsc('Resumption Token')?>:</label>
  <input id="ListSets_resumptionToken" type="text" name="resumptionToken" class="form-control"/>
  </div>

  <button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>ListRecords</legend>
  <input type="hidden" name="verb" value="ListRecords"/>
  <p class="help-block">Returns a listing of available records.</p>

  <div class="form-group">
  <label for="ListRecord_from" class="control-label"><?=$this->transEsc('From')?>:</label>
  <input id="ListRecord_from" type="text" name="from" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListRecord_until" class="control-label"><?=$this->transEsc('Until')?>:</label>
  <input id="ListRecord_until" type="text" name="until" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListRecord_set" class="control-label"><?=$this->transEsc('Set')?>:</label>
  <input id="ListRecord_set" type="text" name="set" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListRecord_metadataPrefix" class="control-label"><?=$this->transEsc('Metadata Prefix')?>:</label>
  <input id="ListRecord_metadataPrefix" type="text" name="metadataPrefix" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="ListRecord_resumptionToken" class="control-label"><?=$this->transEsc('Resumption Token')?>:</label>
  <input id="ListRecord_resumptionToken" type="text" name="resumptionToken" class="form-control"/>
  </div>

  <button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>
<hr/>


<form method="get" action="<?=$baseUrl?>">
<fieldset>
<legend>GetRecord</legend>
  <input type="hidden" name="verb" value="GetRecord"/>
  <p class="help-block">Returns a single record.</p>

  <div class="form-group">
  <label for="GetRecord_identifier" class="control-label"><?=$this->transEsc('Identifier')?>:</label>
  <input id="GetRecord_identifier" type="text" name="identifier" class="form-control"/>
  </div>
  <div class="form-group">
  <label for="GetRecord_metadataPrefix" class="control-label"><?=$this->transEsc('Metadata Token')?>:</label>
  <input id="GetRecord_metadataPrefix" type="text" name="metadataPrefix" class="form-control"/>
  </div>

  <button class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Go')?>"><?=$this->transEsc('Go')?></button>
</fieldset>
</form>


</div>

<?=$this->render("oai/sidebar.phtml")?>

</div>

<?php
$script = <<<JS
$(".toc").toc();
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
